name: Deploy AWS Service Catalog Product

on:
  push:
    branches:
      - main
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
  AWS_ROLE: ${{ secrets.AWS_ROLE }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_LOG: INFO
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ROLE: ${{ secrets.AWS_ROLE }}
      TF_BACKEND_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
      TF_BACKEND_KEY: ${{ secrets.AWS_BUCKET_KEY_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHub-OIDC-TERRAFORM1

    - name: Set up AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        aws --version
    
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Create Backend Configuration
      run: |
        # echo 'bucket = "${{ secrets.AWS_BUCKET_NAME }}"' > backend.hcl
        # echo 'key    = "${{ secrets.AWS_BUCKET_KEY_NAME }}"' >> backend.hcl
        # echo 'region = "${{ secrets.AWS_REGION }}"' >> backend.hcl  
        cat > backend.tf <<EOF
        terraform {
          backend "s3" {
            bucket = "${{ env.TF_BACKEND_BUCKET }}"
            key    = "${{ env.TF_BACKEND_KEY }}"
            region = "${{ env.AWS_DEFAULT_REGION }}"
          }
        }
        EOF
        pwd
        ls -ltr

    - name: 'Terraform Init'
      working-directory: ./Infrastructure/terraform
      run: |
        pwd
        cat ../../backend.tf
        # terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_KEY_NAME }}" -backend-config="region=${{ secrets.AWS_REGION }}"
        terraform init -backend-config=../../backend.tf
        # terraform init

    - name: 'Terraform Validate'
      run: terraform validate
      working-directory: ./Infrastructure/terraform

    - name: 'Terraform Plan'
      run: terraform plan -backend-config=../../backend.hcl
      working-directory: ./Infrastructure/terraform

    # - name: 'Terraform apply'
    #   run: terraform apply -auto-approve -no-color -backend-config=../../backend.tf
    #   working-directory: ./Infrastructure/terraform

    #- name: Deploy AWS Service Catalog Product
    #  run: |
    #    aws servicecatalog create-product --name MyProduct --owner MyOwner --product-type CLOUD_FORMATION_TEMPLATE --provisioning-artifact-parameters Description=MyProduct,Info={LoadTemplateFromURL=https://example.com/myproduct.json},Name=MyProduct
